# Get editor completions based on the config schema
# "$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol   = "[✗](bold red) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[env_var.ENV]
variable = 'ENV'
default = ''
style = "bold red"
format = "🎯 [$env_value]($style) "

[aws]
format = 'on [$symbol$profile(\($region\))]($style) '
style = "bold blue"

[gcloud]
disabled = true

[git_branch]
symbol = '🌱 '
truncation_symbol = ""

[git_commit]
commit_hash_length = 4
tag_symbol = "🔖"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[🍒 PICKING](bold red)'

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[hostname]
ssh_only = true
format =  "on [$hostname](bold red) "
disabled = false

[nodejs]
format = 'via [🤖 $version](bold green) '

[terraform]
disabled = false
format = '[$version]($style) '

[kubernetes]
disabled = false

[[kubernetes.contexts]]
context_pattern = ".*cluster/(?P<cluster>(.*prod.*)+)"
style = "bold red"
context_alias = "$cluster"

[[kubernetes.contexts]]
context_pattern = "teleport\\..*?-(?P<cluster>.*prod.*)+"
style = "bold red"
context_alias = "[T].$cluster"


[[kubernetes.contexts]]
context_pattern = ".*cluster/(?P<cluster>[\\w-]+)"
style = "bold blue"
context_alias = "$cluster"

[[kubernetes.contexts]]
context_pattern = "teleport\\..*?-(?P<cluster>.*)"
style = "bold blue"
context_alias = "[T].$cluster"

[custom.direnv]
format = "[\\[direnv\\]]($style) "
style = "fg:yellow dimmed"
when = "env | grep -E '^DIRENV_FILE='"

[custom.aws_session]
command = '''
expiration_time=$(date -d "$AWS_CREDENTIAL_EXPIRATION" +%s)
current_time=$(date +%s)
time_left=$((expiration_time - current_time))

if [[ $time_left -gt 0 ]]; then
    hours_left=$((time_left / 3600))
    minutes_left=$(((time_left % 3600) / 60))

    if [[ $hours_left -gt 0 ]]; then
        time_display="${hours_left}h ${minutes_left}m"
    else
        time_display="${minutes_left}m"
    fi

    # show a warning if there are less than 15 minutes left
    if [[ $time_left -lt 900 ]]; then
        echo -e "⚠️\e[31m $time_display left\e[0m"
    else
        echo -e "⌛\e[33;32m $time_display left\e[0m"
    fi
fi
'''
when = '[ -n "$AWS_CREDENTIAL_EXPIRATION" ]'